site_name: Tina4 Documentation
copyright: Copyright &copy; 2025 Tina4
theme:
  favicon: /img/favicon.ico
  name: material
  font:
    text: Roboto
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer
    - search.suggest
    - navigation.sections
    - navigation.path
  palette:
    primary: custom
  custom_dir: custom_theme/

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tina4stack/
      name: Tina4 Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VN5WKXnKbX/
      name: Tina4 Discord
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - offline
  - codeinclude:
      title_mode: pymdownx.tabbed
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.b64
  - pymdownx.betterem
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      use_pygments: true         # use pygments library
      pygments_style: default    # use 'default' style
      noclasses: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.striphtml
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Choosing your tools: IDE - Choosing your tools/index.md
  - Getting Started:
      - Quick Start:
          - Docker: getting-started/-Quick Start/index.md
          - Hello World Website: getting-started/-Quick Start/hello-world.md
      - Requirements: getting-started/-Requirements/index.md
      - Php:
          - Installation: getting-started/php/index.md
          - Basics:
              - Static Website with Twig/Jinja: getting-started/php/-Basics/a-static-website-with-twig.md
              - HTML forms and tokens: getting-started/php/-Basics/b-html-forms-and-tokens.md
              - Creating Routes and REST endpoints: getting-started/php/-Basics/c-creating-routes-and-rest-points.md
              - Environment variable setup using .env files: getting-started/php/-Basics/d-using-env-for-settings.md
              - Connecting to a database: getting-started/php/-Basics/e-connecting-to-a-database.md
              - Annotating End Points for Swagger: getting-started/php/-Basics/f-annotating-api-end-points.md
              - Third party API integrations: getting-started/php/-Basics/g-third-party-api-integrations.md
              - Database Migrations: getting-started/php/-Basics/h-creating-database-migrations.md
              - Using the ORM: getting-started/php/-Basics/i-using-the-orm.md
              - Security and Custom Auth Helper: getting-started/php/-Basics/j-security-and-custom-auth-helper.md
              - SASS & CSS compilation: getting-started/php/-Basics/k-scss-compilation.md
          - Advanced:
              - AJAX support through Tina4Helper.js: getting-started/php/Advanced/a-tina4helper-ajax-overview.md
              - How do I run a daemon service in Tina4: getting-started/php/Advanced/a0-run-a-tina4service.md
              - How to get JWT Tokens and create a custom authentication: getting-started/php/Advanced/a1-how-to-get-jwt-tokens-and-create-a-custom-auth-helper.md
              - Dynamic Routes: getting-started/php/Advanced/b-dynamic-routes-with-route-class.md
              - Middleware and Triggers: getting-started/php/Advanced/c-middleware-and-triggers.md
              - Writing modules and components: getting-started/php/Advanced/d-writing-modules-and-components.md
              - Self Deployment git hook triggers: getting-started/php/Advanced/e-self-deployment-git-hook-triggers.md
              - Reports with Report Manager and built in Report Engine: getting-started/php/Advanced/f-wsiwyg-reporting-with-report-manager.md
              - Annotated Test: getting-started/php/Advanced/g-annotated-tests.md
              - Using the versioning: getting-started/php/Advanced/h-using-the-versioning.md
              - Crud routers: getting-started/php/Advanced/i-crud-routers.md
              - Reading emails: getting-started/php/Advanced/j-reading-emails.md
          - How do I: getting-started/php/How-do-I/index.md
          - Packages: getting-started/php/Packages/index.md
          - Trouble Shooting: getting-started/php/Trouble-shooting/index.md
      - Python:
          - Installation: getting-started/python/index.md
          - Basics:
              - Static Website with Twig/Jinja: getting-started/python/-Basics/a-static-website-with-twig.md
              - Basic Routing: getting-started/python/-Basics/b-first-api-routes.md
              - Posting Forms: getting-started/python/-Basics/b-posting-a-simple-form.md
              - Swagger Annotations: getting-started/python/-Basics/c-swagger-annotations.md
              - Database Connections: getting-started/python/-Basics/d-database-connections.md
              - Database Migrations: getting-started/python/-Basics/e-database-migrations.md
              - Database Queries: getting-started/python/-Basics/f-database-communication.md
              - Session Handling: getting-started/python/-Basics/f-sessions.md
              - Password Hashing and Validation: getting-started/python/-Basics/g-password-hashing.md
          - Advanced:
              - Custom Session Handler: getting-started/python/Advanced/a-create-my-own-session-handler.md
              - Manual Control of the Webservice: getting-started/python/Advanced/b-manually-starting-webservice.md
              - Middleware with Routes: getting-started/python/Advanced/c-attach-middleware-to-routes.md
              - Queues with Producers and Consumers: getting-started/python/Advanced/d-queues-with-producers-and-consumers.md
              - Websockets: getting-started/python/Advanced/e-using-websockets.md
          - How do I: getting-started/python/How-do-I/index.md
  - Project Structure: project-structure/index.md